### ISSUE TITLE
About DiffuRank Code

### ISSUE THREAD

**Issue by JiaoChenGuang-JiaoHan** [tiangeluo/DiffuRank#5]
Hi, tiangeluo. Thanks for your great work! I did not find the part of your code where you search for the top-6 optimal viewpoint. Could you please tell me where it is located? Or has it not been released yet? I am currently engaged in a project to collect professional 3D data and would like to try out your code to see if it can be of assistance. Thank you very much！

**Comment by tiangeluo** [comment]
Hi @JiaoChenGuang-JiaoHan ,

Thank you for your acknowledgement! 

I’ll take care of this in the next few days -- have been tied up with other things for a while.

**Comment by tiangeluo** [comment]
I just updated😁 Could you please take a look?

**Comment by JiaoChenGuang-JiaoHan** [comment]
Hi, tiangeluo. I have seen the code you submitted, thank you very much!
